apiVersion: apps/v1
kind: Deployment
metadata:
  name: learnloop-ui
  namespace: "{{ .Release.Namespace }}"
spec:
  selector:
    matchLabels:
      app: learnloop-ui
  replicas: 3
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: learnloop-ui
    spec:
      containers:
        - name: learnloop-ui
          image: "{{ .Values.image }}/streamlit_app:{{ .Values.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
          - name: AZURE_OPENAI_ENDPOINT
            value: "{{ .Values.azureOpenaiEndpoint }}"
          - name: SURFCONEXT_CLIENT_ID
            value: "{{ .Values.surfconextClientId }}"
          - name: LEARNLOOP_VERSION
            value: "{{ .Chart.AppVersion }}"
          envFrom:
            - secretRef:
                name: learnloop-secret
          {{- if .Values.azure }}
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/etc/secrets"
              readOnly: true
          {{- end }}

      {{- if .Values.azure }}
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "learnloop-secretproviderclass"
      {{- end }}