hostname: learnloop.local
ingressClass: nginx
image: learnloop
tag: latest

surfconextClientId: learnloop-test.datanose.nl
surfconextMetadataUrl: https://connect.test.surfconext.nl/.well-known/openid-configuration
azureOpenaiEndpoint: https://uva-test-learnloop.openai.azure.com

azure:
  keyvaultName: keyvaultName
  resourceGroup: resourceGroupName
  subscriptionId: subscriptionId
  tenantId: tenantId
  clientId: clientId
  identityName: identityName
  secrets:
    - name: learnloop-openai-api-key
      key: OPENAI_API_KEY
    - name: learnloop-cosmos-uri
      key: COSMOS_URI
    - name: learnloop-surfconext-client-secret
      key: SURFCONEXT_CLIENT_SECRET
    - name: learnloop-flask-secret
      key: FLASK_SECRET